### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [enthought/encore#112]
Could you please consider to utilize unittest.mock, as a fallback at least?

**Comment by mdickinson** [comment]
We no longer support Python 2, so it would definitely make sense to replace all uses of `mock` with `unittest.mock`; we've already done that in most other ETS packages.

OTOH, resources are limited, so you may need to wait a while. If you want to speed things up, would you be interested in contributing a PR?

**Comment by mdickinson** [comment]
> If you want to speed things up, [...]

Scratch that. It's a one-line change. PR shortly.

**Comment by pgajdos** [comment]
Thank you!

**Comment by mdickinson** [comment]
Unfortunately, while this particular fix _is_ a one-line change, the rest of the codebase still hasn't really made it to Python 3. I've tried to make some progress on that in #114.
