### ISSUE TITLE
pypy compat

### ISSUE THREAD

**Issue by idella** [enthought/encore#84]
running the suite under pypy, the suite buckles for tests in encore.storage.tests.

---

Ran 432 tests in 90.495s

FAILED (SKIP=46, errors=37)

Can't -Ignore some test files because they all import each other. It seems fairly clear the testsuite was just written for py2.

Most errors are of the type

  File "/usr/lib64/pypy/lib-python/2.7/json/**init**.py", line 283, in load
    **kw)
  File "/usr/lib64/pypy/lib-python/2.7/json/**init**.py", line 332, in loads
    return _pypyjson.loads(s)
ValueError: No JSON object could be decoded: unexpected '' at char 0

They are mostly sourced from abstract_test.py & some from locking_filesystem_store_test.py

**Comment by mdickinson** [comment]
This is long out of date; I'm going to close.

Out of interest, I did try running the current `main` branch under pypy-3.8, and it _mostly_ worked - there appear to be some reference-counting issues with the executor that I haven't dug into. Unfortunately, PyPy support is unlikely to be a focus any time soon.
